project:
  type: website
  output-dir: docs

website:
  title: "Annalise Abraham - MUSA 5080 Portfolio"
  navbar:
    left:
    - href: index.qmd
      text: Home
    - text: Weekly Notes 
      menu:
        - href: weekly-notes/week-01-notes.qmd
          text: Week 1
    - text: Labs
      menu:
        - href: labs/lab1/assignment1_template.qmd
          text: Assignment 1 Census Data Quality for Policy Decisions
    - text: Midterm
      menu:
        - href: midterm/Abraham_Knox_Levin_Presentation.qmd
          text: Presentation Slides
        - href: midterm/Abraham_Knox_Levin_Appendix.qmd
          text: Technical Appendix

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
